[env:pico]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200

; JSON အသုံးပြုနိုင်ရန် ArduinoJson Library ကို ထည့်သွင်းခြင်း
lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
